$schema: 'http://json.schemastore.org/prettierrc'

arrowParens: always
bracketSpacing: true
endOfLine: auto
htmlWhitespaceSensitivity: ignore
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 120
proseWrap: preserve
semi: true
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false
