plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/npm'
    - pkgRoot: dist
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
  - - '@semantic-release/github'
    - assets:
        - path: CHANGELOG.md
          label: Changelog
        - path: dist/*.tgz
          label: NPM Package
