name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          HUSKY: 0
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
